//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InClassVoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchQuestionDone
    {
        public int M_DoneID { get; set; }
        public string ChapterName { get; set; }
        public string ColumnA { get; set; }
        public string ColumnB { get; set; }
        public string Solution { get; set; }
        public Nullable<double> Mark { get; set; }
        public Nullable<int> StudentReceive { get; set; }
        public Nullable<int> CorrectNumber { get; set; }
        public Nullable<int> Time { get; set; }
    }
}
