//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InClassVoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionDone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionDone()
        {
            this.QuestionAnswerDones = new HashSet<QuestionAnswerDone>();
        }
    
        public int Q_DoneID { get; set; }
        public Nullable<int> PassageID { get; set; }
        public string Text { get; set; }
        public Nullable<double> Mark { get; set; }
        public int Qtype { get; set; }
        public Nullable<bool> MixChoice { get; set; }
        public Nullable<int> Time { get; set; }
        public byte[] ImageData { get; set; }
        public string ChapterName { get; set; }
    
        public virtual Passage_Done Passage_Done { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionAnswerDone> QuestionAnswerDones { get; set; }
    }
}
