//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InClassVoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_QuizDone
    {
        public int Q_qDoneID { get; set; }
        public Nullable<int> QuizID { get; set; }
        public Nullable<int> QuizDoneID { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual QuizDone QuizDone { get; set; }
    }
}
