//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InClassVoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public int QuizID { get; set; }
        public string QuizName { get; set; }
        public int CourseID { get; set; }
        public string Questions { get; set; }
        public Nullable<int> NumOfQuestion { get; set; }
        public Nullable<double> Mark { get; set; }
        public Nullable<bool> MixQuestion { get; set; }
        public Nullable<int> MixQuestionNumber { get; set; }
        public string StudentGuide { get; set; }
        public string Status { get; set; }
        public Nullable<int> Time { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
